// <auto-generated />
using System;
using EcoScolarWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoScolarWebApi.Migrations
{
    [DbContext(typeof(EcoscolarDbContext))]
    [Migration("20260614174332_UpdateDisputeWithEnums")]
    partial class UpdateDisputeWithEnums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoScolarWebApi.Models.AbuseReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<string>("ReporterUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TargetAdvertId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TargetCommentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("TargetAdvertId");

                    b.HasIndex("TargetCommentId");

                    b.ToTable("AbuseReports");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Advert", b =>
                {
                    b.Property<long>("AdvertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AdvertId");

                    b.HasIndex("SellerId");

                    b.ToTable("Adverts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.BookCategory", b =>
                {
                    b.Property<long>("BookCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookCategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameIt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookCategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookCategoryId = 1L,
                            Description = "Manuels par niveau et programme cantonal.",
                            Name = "Textbooks",
                            NameDe = "Schulbücher",
                            NameFr = "Manuels scolaires",
                            NameIt = "Libri di scuola"
                        },
                        new
                        {
                            BookCategoryId = 2L,
                            Description = "Ouvrages de référence pour les étudiants.",
                            Name = "Reference works",
                            NameDe = "Referenzwerke",
                            NameFr = "Ouvrages de référence",
                            NameIt = "Opere di riferimento"
                        },
                        new
                        {
                            BookCategoryId = 3L,
                            Description = "Cours et ressources pour l'apprentissage des langues.",
                            Name = "Languages",
                            NameDe = "Sprachen",
                            NameFr = "Langues",
                            NameIt = "Lingue"
                        },
                        new
                        {
                            BookCategoryId = 4L,
                            Description = "Manuels et ressources pour l'enseignement des mathématiques.",
                            Name = "Mathematics",
                            NameDe = "Mathematik",
                            NameFr = "Mathématiques",
                            NameIt = "Matematica"
                        },
                        new
                        {
                            BookCategoryId = 5L,
                            Description = "Cours et ressources pour les sciences naturelles.",
                            Name = "Natural Sciences",
                            NameDe = "Naturwissenschaften",
                            NameFr = "Sciences naturelles",
                            NameIt = "Scienze della natura"
                        },
                        new
                        {
                            BookCategoryId = 6L,
                            Description = "Cours et ressources pour l'histoire et la géographie.",
                            Name = "History and Geography",
                            NameDe = "Geschichte und Geographie",
                            NameFr = "Histoire et géographie",
                            NameIt = "Storia e geografia"
                        },
                        new
                        {
                            BookCategoryId = 7L,
                            Description = "Cours et ressources pour l'économie et le droit.",
                            Name = "Economics and Law",
                            NameDe = "Wirtschaft und Recht",
                            NameFr = "Économie et droit",
                            NameIt = "Economia e diritto"
                        },
                        new
                        {
                            BookCategoryId = 8L,
                            Description = "Cours et ressources pour les arts et la musique.",
                            Name = "Arts and Music",
                            NameDe = "Kunst und Musik",
                            NameFr = "Arts et musique",
                            NameIt = "Arte e musica"
                        },
                        new
                        {
                            BookCategoryId = 9L,
                            Description = "Cours et ressources pour l'informatique.",
                            Name = "Computer Science",
                            NameDe = "Informatik",
                            NameFr = "Informatique",
                            NameIt = "Informatica"
                        },
                        new
                        {
                            BookCategoryId = 10L,
                            Description = "Cours et ressources pour la formation professionnelle.",
                            Name = "Vocational training",
                            NameDe = "Berufliche Bildung",
                            NameFr = "Formation professionnelle",
                            NameIt = "Formazione professionale"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Dispute", b =>
                {
                    b.Property<int>("DisputeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisputeId"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("DisputeId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Flag", b =>
                {
                    b.Property<int>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlagId"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FlaggedId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FlagId");

                    b.HasIndex("FlaggedId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Language", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameIt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Label");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Label = "FR",
                            Name = "French",
                            NameDe = "Französisch",
                            NameFr = "Français",
                            NameIt = "Francese"
                        },
                        new
                        {
                            Label = "DE",
                            Name = "German",
                            NameDe = "Deutsch",
                            NameFr = "Allemand",
                            NameIt = "Tedesco"
                        },
                        new
                        {
                            Label = "IT",
                            Name = "Italian",
                            NameDe = "Italien",
                            NameFr = "Italien",
                            NameIt = "Italiano"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Picture", b =>
                {
                    b.Property<long>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PictureId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PhysicalItemId")
                        .HasColumnType("bigint");

                    b.HasKey("PictureId");

                    b.HasIndex("PhysicalItemId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PriceOffer", b =>
                {
                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdvertId", "BuyerId");

                    b.HasIndex("BuyerId");

                    b.ToTable("PriceOffers");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.ProductCategory", b =>
                {
                    b.Property<long>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductCategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameIt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductCategoryId = 1L,
                            Description = "Papiers, enveloppes, étiquettes et consommables.",
                            Name = "Stationery",
                            NameDe = "Papierware",
                            NameFr = "Papeterie",
                            NameIt = "Cartoleria"
                        },
                        new
                        {
                            ProductCategoryId = 2L,
                            Description = "Stylos, crayons, feutres et surligneurs.",
                            Name = "Writing supplies",
                            NameDe = "Schreibmaterial",
                            NameFr = "Matériel d'écriture",
                            NameIt = "Materiale da scrittura"
                        },
                        new
                        {
                            ProductCategoryId = 3L,
                            Description = "Cahiers, classeurs, intercalaires et chemises.",
                            Name = "Notebooks and binders",
                            NameDe = "Hefte und Mappe",
                            NameFr = "Cahiers et classeurs",
                            NameIt = "Quaderni e cartelle"
                        },
                        new
                        {
                            ProductCategoryId = 4L,
                            Description = "Peinture, pinceaux, papiers dessin et outils créatifs.",
                            Name = "Art supplies",
                            NameDe = "Künstlerisches Material",
                            NameFr = "Matériel artistique",
                            NameIt = "Materiale artistico"
                        },
                        new
                        {
                            ProductCategoryId = 5L,
                            Description = "Kits pédagogiques, microscopes et accessoires.",
                            Name = "Scientific equipment",
                            NameDe = "Wissenschaftliches Material",
                            NameFr = "Matériel scientifique",
                            NameIt = "Materiale scientifico"
                        },
                        new
                        {
                            ProductCategoryId = 6L,
                            Description = "Ballons, cordes, protections et matériel EPS.",
                            Name = "Sports equipment",
                            NameDe = "Sportausrüstung",
                            NameFr = "Équipement sportif",
                            NameIt = "Equipaggiamento sportivo"
                        },
                        new
                        {
                            ProductCategoryId = 7L,
                            Description = "Claviers, souris, périphériques et accessoires.",
                            Name = "Computer equipment",
                            NameDe = "Informatikmaterial",
                            NameFr = "Matériel informatique",
                            NameIt = "Materiale informatico"
                        },
                        new
                        {
                            ProductCategoryId = 8L,
                            Description = "Sacs d'école, cartables et trousses.",
                            Name = "School bags and cases",
                            NameDe = "Schulrucksäcke und Bücherfächer",
                            NameFr = "Sacs et cartables",
                            NameIt = "Ziole e borse scolastiche"
                        },
                        new
                        {
                            ProductCategoryId = 9L,
                            Description = "Calculatrices scientifiques et financières.",
                            Name = "Calculators",
                            NameDe = "Taschenrechner",
                            NameFr = "Calculatrices",
                            NameIt = "Calcolatrici"
                        },
                        new
                        {
                            ProductCategoryId = 10L,
                            Description = "Blouses, lunettes de protection et consommables.",
                            Name = "Laboratory supplies",
                            NameDe = "Laboratoriumsausrüstung",
                            NameFr = "Accessoires de laboratoire",
                            NameIt = "Accessori del laboratorio"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PublicComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CommentId");

                    b.HasIndex("AdvertId");

                    b.HasIndex("AuthorId");

                    b.ToTable("PublicComments");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewedId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReviewedRole")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("ReviewId");

                    b.HasIndex("ReviewedId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TransactionId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SchoolGrade", b =>
                {
                    b.Property<long>("SchoolGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SchoolGradeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameIt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SchoolGradeId");

                    b.ToTable("SchoolGrades");

                    b.HasData(
                        new
                        {
                            SchoolGradeId = 1L,
                            Code = "C1",
                            Name = "Cycle 1 (Grades 1–4)",
                            NameDe = "Stufe 1 (1H-4H)",
                            NameFr = "Cycle 1 (1H-4H)",
                            NameIt = "Livello 1 (1H-4H)"
                        },
                        new
                        {
                            SchoolGradeId = 2L,
                            Code = "C2",
                            Name = "Cycle 2 (Grades 5–8)",
                            NameDe = "Stufe 2 (5H-8H)",
                            NameFr = "Cycle 2 (5H-8H)",
                            NameIt = "Livello 2 (5H-8H)"
                        },
                        new
                        {
                            SchoolGradeId = 3L,
                            Code = "C3",
                            Name = "Cycle 3 (Grades 9–11)",
                            NameDe = "Stufe 3 (9H-11H)",
                            NameFr = "Cycle 3 (9H-11H)",
                            NameIt = "Livello 3 (9H-11H)"
                        },
                        new
                        {
                            SchoolGradeId = 4L,
                            Code = "S2-GYM",
                            Name = "Upper Secondary School - High School",
                            NameDe = "Sekundarstufe II - Gymnasium",
                            NameFr = "Secondaire II - Gymnase",
                            NameIt = "Secondaria II - Ginnasio"
                        },
                        new
                        {
                            SchoolGradeId = 5L,
                            Code = "S2-MP",
                            Name = "Upper Secondary Level – Vocational Maturity",
                            NameDe = "Sekundarstufe II - Berufsmaturität",
                            NameFr = "Secondaire II - Maturité professionnelle",
                            NameIt = "Secondaria II - Maturità professionale"
                        },
                        new
                        {
                            SchoolGradeId = 6L,
                            Code = "S2-CFC",
                            Name = "Upper Secondary School – CFC",
                            NameDe = "Sekundarstufe II - CFC",
                            NameFr = "Secondaire II - CFC",
                            NameIt = "Secondaria II - CFC"
                        },
                        new
                        {
                            SchoolGradeId = 7L,
                            Code = "S2-ECG",
                            Name = "Upper Secondary Level - ECG",
                            NameDe = "Sekundarstufe II - ECG",
                            NameFr = "Secondaire II - ECG",
                            NameIt = "Secondaria II - ECG"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SearchAlert", b =>
                {
                    b.Property<int>("ResearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchId"));

                    b.Property<string>("AdvertSearch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdvertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BookCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SchoolGradeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ResearchId");

                    b.HasIndex("BookCategoryId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("SchoolGradeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("SearchAlerts");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Subject", b =>
                {
                    b.Property<long>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubjectId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameIt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1L,
                            Code = "FR",
                            Name = "French",
                            NameDe = "Französisch",
                            NameFr = "Français",
                            NameIt = "Francese"
                        },
                        new
                        {
                            SubjectId = 2L,
                            Code = "DE",
                            Name = "German",
                            NameDe = "Deutsch",
                            NameFr = "Allemand",
                            NameIt = "Tedesco"
                        },
                        new
                        {
                            SubjectId = 3L,
                            Code = "EN",
                            Name = "English",
                            NameDe = "Englisch",
                            NameFr = "Anglais",
                            NameIt = "Inglese"
                        },
                        new
                        {
                            SubjectId = 4L,
                            Code = "MATH",
                            Name = "Mathematics",
                            NameDe = "Mathematik",
                            NameFr = "Mathématiques",
                            NameIt = "Matematica"
                        },
                        new
                        {
                            SubjectId = 5L,
                            Code = "SCI",
                            Name = "Natural Sciences",
                            NameDe = "Naturwissenschaften",
                            NameFr = "Sciences naturelles",
                            NameIt = "Scienze della natura"
                        },
                        new
                        {
                            SubjectId = 6L,
                            Code = "HIST",
                            Name = "History",
                            NameDe = "Geschichte",
                            NameFr = "Histoire",
                            NameIt = "Storia"
                        },
                        new
                        {
                            SubjectId = 7L,
                            Code = "GEO",
                            Name = "Geography",
                            NameDe = "Geographie",
                            NameFr = "Géographie",
                            NameIt = "Geografia"
                        },
                        new
                        {
                            SubjectId = 8L,
                            Code = "EPS",
                            Name = "Physical Education",
                            NameDe = "Physikalische Bildung",
                            NameFr = "Éducation physique",
                            NameIt = "Educazione fisica"
                        },
                        new
                        {
                            SubjectId = 9L,
                            Code = "ARTS",
                            Name = "Visual Arts",
                            NameDe = "Visuelle Künste",
                            NameFr = "Arts visuels",
                            NameIt = "Arti visive"
                        },
                        new
                        {
                            SubjectId = 10L,
                            Code = "MUS",
                            Name = "Music",
                            NameDe = "Musik",
                            NameFr = "Musique",
                            NameIt = "Musica"
                        },
                        new
                        {
                            SubjectId = 11L,
                            Code = "ECO",
                            Name = "Economics and Law",
                            NameDe = "Wirtschaft und Recht",
                            NameFr = "Économie et droit",
                            NameIt = "Economia e diritto"
                        },
                        new
                        {
                            SubjectId = 12L,
                            Code = "INFO",
                            Name = "Computer Science",
                            NameDe = "Informatik",
                            NameFr = "Informatique",
                            NameIt = "Informatica"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SupportTicketMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFromSupport")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("SupportTicketMessages");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<bool>("BuyerConsent")
                        .HasColumnType("bit");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpirationReservationTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SellerConsent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("AdvertId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStripeOnboarded")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserLanguage", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguageLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "Label");

                    b.HasIndex("Label");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PhysicalItem", b =>
                {
                    b.HasBaseType("EcoScolarWebApi.Models.Advert");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("PhysicalItems");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.TutoringAdvert", b =>
                {
                    b.HasBaseType("EcoScolarWebApi.Models.Advert");

                    b.Property<long>("SchoolGradeId")
                        .HasColumnType("bigint");

                    b.Property<string>("StudyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("TeachingLanguage")
                        .HasColumnType("int");

                    b.HasIndex("SchoolGradeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TutoringAdverts");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Book", b =>
                {
                    b.HasBaseType("EcoScolarWebApi.Models.PhysicalItem");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("BookCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("WrittenLanguage")
                        .HasColumnType("int");

                    b.HasIndex("BookCategoryId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.AbuseReport", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.Advert", "TargetAdvert")
                        .WithMany()
                        .HasForeignKey("TargetAdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.PublicComment", "TargetComment")
                        .WithMany()
                        .HasForeignKey("TargetCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Reporter");

                    b.Navigation("TargetAdvert");

                    b.Navigation("TargetComment");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Advert", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.CartItem", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Dispute", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Flag", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", "Flagged")
                        .WithMany()
                        .HasForeignKey("FlaggedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flagged");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Picture", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.PhysicalItem", "PhysicalItem")
                        .WithMany("Pictures")
                        .HasForeignKey("PhysicalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysicalItem");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PriceOffer", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PublicComment", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Review", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", "Reviewed")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("ReviewedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewed");

                    b.Navigation("Reviewer");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SearchAlert", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.BookCategory", "BookCategory")
                        .WithMany()
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoScolarWebApi.Models.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId");

                    b.HasOne("EcoScolarWebApi.Models.SchoolGrade", "SchoolGrade")
                        .WithMany()
                        .HasForeignKey("SchoolGradeId");

                    b.HasOne("EcoScolarWebApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoScolarWebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCategory");

                    b.Navigation("ProductCategory");

                    b.Navigation("SchoolGrade");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SupportTicket", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SupportTicketMessage", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Transaction", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.User", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserFavorite", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserLanguage", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "User")
                        .WithMany("Languages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PhysicalItem", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", null)
                        .WithOne()
                        .HasForeignKey("EcoScolarWebApi.Models.PhysicalItem", "AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.TutoringAdvert", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", null)
                        .WithOne()
                        .HasForeignKey("EcoScolarWebApi.Models.TutoringAdvert", "AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.SchoolGrade", "SchoolGrade")
                        .WithMany()
                        .HasForeignKey("SchoolGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolGrade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Book", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.PhysicalItem", null)
                        .WithOne()
                        .HasForeignKey("EcoScolarWebApi.Models.Book", "AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.BookCategory", "BookCategory")
                        .WithMany()
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCategory");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Location", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Favorites");

                    b.Navigation("Languages");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PhysicalItem", b =>
                {
                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
