// <auto-generated />
using System;
using EcoscolarWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoScolarWebApi.Migrations
{
    [DbContext(typeof(EcoscolarDbContext))]
    partial class EcoscolarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoscolarWebApi.Models.Adverts", b =>
                {
                    b.Property<long>("AdvertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AdvertId");

                    b.HasIndex("UserId");

                    b.ToTable("Adverts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.BookCategories", b =>
                {
                    b.Property<long>("BookCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookCategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookCategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookCategoryId = 1L,
                            Description = "Manuels par niveau et programme cantonal.",
                            Name = "Manuels scolaires"
                        },
                        new
                        {
                            BookCategoryId = 2L,
                            Description = "Dictionnaires, encyclopédies et atlas scolaires.",
                            Name = "Ouvrages de référence"
                        },
                        new
                        {
                            BookCategoryId = 3L,
                            Description = "Français, allemand, italien, anglais et langues locales.",
                            Name = "Langues"
                        },
                        new
                        {
                            BookCategoryId = 4L,
                            Description = "Supports de mathématiques pour cycles 1 à secondaire II.",
                            Name = "Mathématiques"
                        },
                        new
                        {
                            BookCategoryId = 5L,
                            Description = "Biologie, chimie, physique et sciences de la nature.",
                            Name = "Sciences naturelles"
                        },
                        new
                        {
                            BookCategoryId = 6L,
                            Description = "Histoire suisse, géographie et éducation citoyenne.",
                            Name = "Histoire et géographie"
                        },
                        new
                        {
                            BookCategoryId = 7L,
                            Description = "Introduction à l'économie, droit et gestion.",
                            Name = "Économie et droit"
                        },
                        new
                        {
                            BookCategoryId = 8L,
                            Description = "Supports pour arts visuels, musique et activités créatives.",
                            Name = "Arts et musique"
                        },
                        new
                        {
                            BookCategoryId = 9L,
                            Description = "Initiation au numérique, algorithmique et outils informatiques.",
                            Name = "Informatique"
                        },
                        new
                        {
                            BookCategoryId = 10L,
                            Description = "Manuels liés aux filières CFC et maturité professionnelle.",
                            Name = "Formation professionnelle"
                        });
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Language", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Label");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Label = "FR",
                            Name = "Français"
                        },
                        new
                        {
                            Label = "DE",
                            Name = "Deutsch"
                        },
                        new
                        {
                            Label = "IT",
                            Name = "Italian"
                        });
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            City = "Lausanne",
                            PostalCode = "1000",
                            Region = "Vaud"
                        },
                        new
                        {
                            LocationId = 2,
                            City = "Montreux",
                            PostalCode = "1820",
                            Region = "Vaud"
                        },
                        new
                        {
                            LocationId = 3,
                            City = "Martigny",
                            PostalCode = "1920",
                            Region = "Valais"
                        });
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Pictures", b =>
                {
                    b.Property<long>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PictureId"));

                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("PictureId");

                    b.HasIndex("AdvertId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.ProductCategories", b =>
                {
                    b.Property<long>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductCategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductCategoryId = 1L,
                            Description = "Papiers, enveloppes, étiquettes et consommables.",
                            Name = "Papeterie"
                        },
                        new
                        {
                            ProductCategoryId = 2L,
                            Description = "Stylos, crayons, feutres et surligneurs.",
                            Name = "Matériel d'écriture"
                        },
                        new
                        {
                            ProductCategoryId = 3L,
                            Description = "Cahiers, classeurs, intercalaires et chemises.",
                            Name = "Cahiers et classeurs"
                        },
                        new
                        {
                            ProductCategoryId = 4L,
                            Description = "Peinture, pinceaux, papiers dessin et outils créatifs.",
                            Name = "Matériel artistique"
                        },
                        new
                        {
                            ProductCategoryId = 5L,
                            Description = "Kits pédagogiques, microscopes et accessoires.",
                            Name = "Matériel scientifique"
                        },
                        new
                        {
                            ProductCategoryId = 6L,
                            Description = "Ballons, cordes, protections et matériel EPS.",
                            Name = "Équipement sportif"
                        },
                        new
                        {
                            ProductCategoryId = 7L,
                            Description = "Claviers, souris, périphériques et accessoires.",
                            Name = "Matériel informatique"
                        },
                        new
                        {
                            ProductCategoryId = 8L,
                            Description = "Sacs d'école, cartables et trousses.",
                            Name = "Sacs et cartables"
                        },
                        new
                        {
                            ProductCategoryId = 9L,
                            Description = "Calculatrices scientifiques et financières.",
                            Name = "Calculatrices"
                        },
                        new
                        {
                            ProductCategoryId = 10L,
                            Description = "Blouses, lunettes de protection et consommables.",
                            Name = "Accessoires de laboratoire"
                        });
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.SchoolGrades", b =>
                {
                    b.Property<long>("SchoolGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SchoolGradeId"));

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SchoolGradeId");

                    b.ToTable("SchoolGrades");

                    b.HasData(
                        new
                        {
                            SchoolGradeId = 1L,
                            Grade = "C1",
                            Name = "Cycle 1 (1H-4H)"
                        },
                        new
                        {
                            SchoolGradeId = 2L,
                            Grade = "C2",
                            Name = "Cycle 2 (5H-8H)"
                        },
                        new
                        {
                            SchoolGradeId = 3L,
                            Grade = "C3",
                            Name = "Cycle 3 (9H-11H)"
                        },
                        new
                        {
                            SchoolGradeId = 4L,
                            Grade = "S2-GYM",
                            Name = "Secondaire II - Gymnase"
                        },
                        new
                        {
                            SchoolGradeId = 5L,
                            Grade = "S2-MP",
                            Name = "Secondaire II - Maturité professionnelle"
                        },
                        new
                        {
                            SchoolGradeId = 6L,
                            Grade = "S2-CFC",
                            Name = "Secondaire II - CFC"
                        },
                        new
                        {
                            SchoolGradeId = 7L,
                            Grade = "S2-ECG",
                            Name = "Secondaire II - ECG"
                        });
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Subjects", b =>
                {
                    b.Property<long>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubjectId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1L,
                            Code = "FR",
                            Name = "Français"
                        },
                        new
                        {
                            SubjectId = 2L,
                            Code = "DE",
                            Name = "Allemand"
                        },
                        new
                        {
                            SubjectId = 3L,
                            Code = "EN",
                            Name = "Anglais"
                        },
                        new
                        {
                            SubjectId = 4L,
                            Code = "MATH",
                            Name = "Mathématiques"
                        },
                        new
                        {
                            SubjectId = 5L,
                            Code = "SCI",
                            Name = "Sciences naturelles"
                        },
                        new
                        {
                            SubjectId = 6L,
                            Code = "HIST",
                            Name = "Histoire"
                        },
                        new
                        {
                            SubjectId = 7L,
                            Code = "GEO",
                            Name = "Géographie"
                        },
                        new
                        {
                            SubjectId = 8L,
                            Code = "EPS",
                            Name = "Éducation physique"
                        },
                        new
                        {
                            SubjectId = 9L,
                            Code = "ARTS",
                            Name = "Arts visuels"
                        },
                        new
                        {
                            SubjectId = 10L,
                            Code = "MUS",
                            Name = "Musique"
                        },
                        new
                        {
                            SubjectId = 11L,
                            Code = "ECO",
                            Name = "Économie et droit"
                        },
                        new
                        {
                            SubjectId = 12L,
                            Code = "INFO",
                            Name = "Informatique"
                        });
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BirthdayDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.UserLanguage", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguageLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "Label");

                    b.HasIndex("Label");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.AdvertServices", b =>
                {
                    b.HasBaseType("EcoscolarWebApi.Models.Adverts");

                    b.Property<long>("SchoolGradeId")
                        .HasColumnType("bigint");

                    b.Property<string>("StudyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("TeachingLanguage")
                        .HasColumnType("int");

                    b.HasIndex("SchoolGradeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.PhysicalItems", b =>
                {
                    b.HasBaseType("EcoscolarWebApi.Models.Adverts");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("PhysicalItems");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Books", b =>
                {
                    b.HasBaseType("EcoscolarWebApi.Models.PhysicalItems");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("BookCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("WrittenLanguage")
                        .HasColumnType("int");

                    b.HasIndex("BookCategoryId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Adverts", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Pictures", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.PhysicalItems", "Adverts")
                        .WithMany("Pictures")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.User", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.UserFavorite", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.Adverts", "Adverts")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoscolarWebApi.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Adverts");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.UserLanguage", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoscolarWebApi.Models.User", "User")
                        .WithMany("Languages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoscolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.AdvertServices", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.Adverts", null)
                        .WithOne()
                        .HasForeignKey("EcoscolarWebApi.Models.AdvertServices", "AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoscolarWebApi.Models.SchoolGrades", "SchoolGrades")
                        .WithMany("AdvertServices")
                        .HasForeignKey("SchoolGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoscolarWebApi.Models.Subjects", "Subjects")
                        .WithMany("AdvertServices")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolGrades");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.PhysicalItems", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.Adverts", null)
                        .WithOne()
                        .HasForeignKey("EcoscolarWebApi.Models.PhysicalItems", "AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoscolarWebApi.Models.ProductCategories", "ProductCategories")
                        .WithMany("PhysicalItems")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Books", b =>
                {
                    b.HasOne("EcoscolarWebApi.Models.PhysicalItems", null)
                        .WithOne()
                        .HasForeignKey("EcoscolarWebApi.Models.Books", "AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoscolarWebApi.Models.BookCategories", "BookCategories")
                        .WithMany("Books")
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.BookCategories", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Location", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.ProductCategories", b =>
                {
                    b.Navigation("PhysicalItems");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.SchoolGrades", b =>
                {
                    b.Navigation("AdvertServices");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.Subjects", b =>
                {
                    b.Navigation("AdvertServices");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("EcoscolarWebApi.Models.PhysicalItems", b =>
                {
                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
