// <auto-generated />
using System;
using EcoScolarWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoScolarWebApi.Migrations
{
    [DbContext(typeof(EcoscolarDbContext))]
    partial class EcoscolarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoScolarWebApi.Models.Advert", b =>
                {
                    b.Property<long>("AdvertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AdvertId");

                    b.HasIndex("SellerId");

                    b.ToTable("Adverts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.BookCategory", b =>
                {
                    b.Property<long>("BookCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookCategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookCategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookCategoryId = 1L,
                            Description = "Manuels par niveau et programme cantonal.",
                            Name = "Manuels scolaires"
                        },
                        new
                        {
                            BookCategoryId = 2L,
                            Description = "Dictionnaires, encyclopédies et atlas scolaires.",
                            Name = "Ouvrages de référence"
                        },
                        new
                        {
                            BookCategoryId = 3L,
                            Description = "Français, allemand, italien, anglais et langues locales.",
                            Name = "Langues"
                        },
                        new
                        {
                            BookCategoryId = 4L,
                            Description = "Supports de mathématiques pour cycles 1 à secondaire II.",
                            Name = "Mathématiques"
                        },
                        new
                        {
                            BookCategoryId = 5L,
                            Description = "Biologie, chimie, physique et sciences de la nature.",
                            Name = "Sciences naturelles"
                        },
                        new
                        {
                            BookCategoryId = 6L,
                            Description = "Histoire suisse, géographie et éducation citoyenne.",
                            Name = "Histoire et géographie"
                        },
                        new
                        {
                            BookCategoryId = 7L,
                            Description = "Introduction à l'économie, droit et gestion.",
                            Name = "Économie et droit"
                        },
                        new
                        {
                            BookCategoryId = 8L,
                            Description = "Supports pour arts visuels, musique et activités créatives.",
                            Name = "Arts et musique"
                        },
                        new
                        {
                            BookCategoryId = 9L,
                            Description = "Initiation au numérique, algorithmique et outils informatiques.",
                            Name = "Informatique"
                        },
                        new
                        {
                            BookCategoryId = 10L,
                            Description = "Manuels liés aux filières CFC et maturité professionnelle.",
                            Name = "Formation professionnelle"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Dispute", b =>
                {
                    b.Property<int>("DisputeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisputeId"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("DisputeId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Flag", b =>
                {
                    b.Property<int>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlagId"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FlaggedId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FlagId");

                    b.HasIndex("FlaggedId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Language", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Label");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Label = "FR",
                            Name = "Français"
                        },
                        new
                        {
                            Label = "DE",
                            Name = "Deutsch"
                        },
                        new
                        {
                            Label = "IT",
                            Name = "Italian"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            City = "Lausanne",
                            PostalCode = "1000",
                            Region = "Vaud"
                        },
                        new
                        {
                            LocationId = 2,
                            City = "Montreux",
                            PostalCode = "1820",
                            Region = "Vaud"
                        },
                        new
                        {
                            LocationId = 3,
                            City = "Martigny",
                            PostalCode = "1920",
                            Region = "Valais"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Picture", b =>
                {
                    b.Property<long>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PictureId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PhysicalItemId")
                        .HasColumnType("bigint");

                    b.HasKey("PictureId");

                    b.HasIndex("PhysicalItemId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PriceOffer", b =>
                {
                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdvertId", "BuyerId");

                    b.HasIndex("BuyerId");

                    b.ToTable("PriceOffers");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.ProductCategory", b =>
                {
                    b.Property<long>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductCategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductCategoryId = 1L,
                            Description = "Papiers, enveloppes, étiquettes et consommables.",
                            Name = "Papeterie"
                        },
                        new
                        {
                            ProductCategoryId = 2L,
                            Description = "Stylos, crayons, feutres et surligneurs.",
                            Name = "Matériel d'écriture"
                        },
                        new
                        {
                            ProductCategoryId = 3L,
                            Description = "Cahiers, classeurs, intercalaires et chemises.",
                            Name = "Cahiers et classeurs"
                        },
                        new
                        {
                            ProductCategoryId = 4L,
                            Description = "Peinture, pinceaux, papiers dessin et outils créatifs.",
                            Name = "Matériel artistique"
                        },
                        new
                        {
                            ProductCategoryId = 5L,
                            Description = "Kits pédagogiques, microscopes et accessoires.",
                            Name = "Matériel scientifique"
                        },
                        new
                        {
                            ProductCategoryId = 6L,
                            Description = "Ballons, cordes, protections et matériel EPS.",
                            Name = "Équipement sportif"
                        },
                        new
                        {
                            ProductCategoryId = 7L,
                            Description = "Claviers, souris, périphériques et accessoires.",
                            Name = "Matériel informatique"
                        },
                        new
                        {
                            ProductCategoryId = 8L,
                            Description = "Sacs d'école, cartables et trousses.",
                            Name = "Sacs et cartables"
                        },
                        new
                        {
                            ProductCategoryId = 9L,
                            Description = "Calculatrices scientifiques et financières.",
                            Name = "Calculatrices"
                        },
                        new
                        {
                            ProductCategoryId = 10L,
                            Description = "Blouses, lunettes de protection et consommables.",
                            Name = "Accessoires de laboratoire"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PublicComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CommentId");

                    b.HasIndex("AdvertId");

                    b.HasIndex("AuthorId");

                    b.ToTable("PublicComments");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("ReviewId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SchoolGrade", b =>
                {
                    b.Property<long>("SchoolGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SchoolGradeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SchoolGradeId");

                    b.ToTable("SchoolGrades");

                    b.HasData(
                        new
                        {
                            SchoolGradeId = 1L,
                            Code = "C1",
                            Name = "Cycle 1 (1H-4H)"
                        },
                        new
                        {
                            SchoolGradeId = 2L,
                            Code = "C2",
                            Name = "Cycle 2 (5H-8H)"
                        },
                        new
                        {
                            SchoolGradeId = 3L,
                            Code = "C3",
                            Name = "Cycle 3 (9H-11H)"
                        },
                        new
                        {
                            SchoolGradeId = 4L,
                            Code = "S2-GYM",
                            Name = "Secondaire II - Gymnase"
                        },
                        new
                        {
                            SchoolGradeId = 5L,
                            Code = "S2-MP",
                            Name = "Secondaire II - Maturité professionnelle"
                        },
                        new
                        {
                            SchoolGradeId = 6L,
                            Code = "S2-CFC",
                            Name = "Secondaire II - CFC"
                        },
                        new
                        {
                            SchoolGradeId = 7L,
                            Code = "S2-ECG",
                            Name = "Secondaire II - ECG"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SearchAlert", b =>
                {
                    b.Property<int>("ResearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchId"));

                    b.Property<string>("AdvertSearch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdvertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BookCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ResearchId");

                    b.HasIndex("BookCategoryId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("SearchAlerts");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Subject", b =>
                {
                    b.Property<long>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubjectId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1L,
                            Code = "FR",
                            Name = "Français"
                        },
                        new
                        {
                            SubjectId = 2L,
                            Code = "DE",
                            Name = "Allemand"
                        },
                        new
                        {
                            SubjectId = 3L,
                            Code = "EN",
                            Name = "Anglais"
                        },
                        new
                        {
                            SubjectId = 4L,
                            Code = "MATH",
                            Name = "Mathématiques"
                        },
                        new
                        {
                            SubjectId = 5L,
                            Code = "SCI",
                            Name = "Sciences naturelles"
                        },
                        new
                        {
                            SubjectId = 6L,
                            Code = "HIST",
                            Name = "Histoire"
                        },
                        new
                        {
                            SubjectId = 7L,
                            Code = "GEO",
                            Name = "Géographie"
                        },
                        new
                        {
                            SubjectId = 8L,
                            Code = "EPS",
                            Name = "Éducation physique"
                        },
                        new
                        {
                            SubjectId = 9L,
                            Code = "ARTS",
                            Name = "Arts visuels"
                        },
                        new
                        {
                            SubjectId = 10L,
                            Code = "MUS",
                            Name = "Musique"
                        },
                        new
                        {
                            SubjectId = 11L,
                            Code = "ECO",
                            Name = "Économie et droit"
                        },
                        new
                        {
                            SubjectId = 12L,
                            Code = "INFO",
                            Name = "Informatique"
                        });
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<bool>("BuyerConsent")
                        .HasColumnType("bit");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpirationReservationTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SellerConsent")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("AdvertId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AdvertId")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserLanguage", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguageLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "Label");

                    b.HasIndex("Label");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserSearchAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Q")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSearchAlerts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PhysicalItem", b =>
                {
                    b.HasBaseType("EcoScolarWebApi.Models.Advert");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("PhysicalItems");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.TutoringAdvert", b =>
                {
                    b.HasBaseType("EcoScolarWebApi.Models.Advert");

                    b.Property<long>("SchoolGradeId")
                        .HasColumnType("bigint");

                    b.Property<string>("StudyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("TeachingLanguage")
                        .HasColumnType("int");

                    b.HasIndex("SchoolGradeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TutoringAdverts");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Book", b =>
                {
                    b.HasBaseType("EcoScolarWebApi.Models.PhysicalItem");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("BookCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("WrittenLanguage")
                        .HasColumnType("int");

                    b.HasIndex("BookCategoryId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Advert", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Dispute", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Flag", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", "Flagged")
                        .WithMany()
                        .HasForeignKey("FlaggedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flagged");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Picture", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.PhysicalItem", "PhysicalItem")
                        .WithMany("Pictures")
                        .HasForeignKey("PhysicalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysicalItem");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PriceOffer", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PublicComment", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Review", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.SearchAlert", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.BookCategory", "BookCategory")
                        .WithMany()
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoScolarWebApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoScolarWebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCategory");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Transaction", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.User", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserFavorite", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserLanguage", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", "User")
                        .WithMany("Languages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.UserSearchAlert", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PhysicalItem", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", null)
                        .WithOne()
                        .HasForeignKey("EcoScolarWebApi.Models.PhysicalItem", "AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.TutoringAdvert", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.Advert", null)
                        .WithOne()
                        .HasForeignKey("EcoScolarWebApi.Models.TutoringAdvert", "AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.SchoolGrade", "SchoolGrade")
                        .WithMany()
                        .HasForeignKey("SchoolGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolGrade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Book", b =>
                {
                    b.HasOne("EcoScolarWebApi.Models.PhysicalItem", null)
                        .WithOne()
                        .HasForeignKey("EcoScolarWebApi.Models.Book", "AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoScolarWebApi.Models.BookCategory", "BookCategory")
                        .WithMany()
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCategory");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.Location", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("EcoScolarWebApi.Models.PhysicalItem", b =>
                {
                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
